kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
data:
  nginx.conf: |
    server {
        listen 80;
    
        server_name app.donwaldhartman.co.za;
    
        location / {
            proxy_pass http://82.165.230.79:30253; # Change this to the appropriate port if your application is not running on port 3000
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
    
    server {
        listen 80;
    
        server_name argo.donwaldhartman.co.za;
    
        location / {
            proxy_pass http://82.165.230.79:8080; # Change this to the appropriate port if your application is not running on port 3000
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }
    }
